# Generated by Django 3.1.6 on 2021-05-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0011_auto_20210217_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_visible_on_main_page',
            field=models.BooleanField(null=True),
        ),
    ]
